-- employee table structure
create table emp_gen.employee_data(
    I_Emp_id INT GENERATED by default AS IDENTITY primary key,
    v_name   varchar,
    D_date_of_joining date,
    V_email varchar,
    I_manager_id  int references emp_gen.employee_data(I_Emp_id)

);

-- function to generate random employee data
CREATE OR REPLACE FUNCTION generate_emp_data(p_rows int) RETURNS void AS
$$
declare 
  V_max_s int;
  V_desig varchar;
  I_con_name int;
  V_rand_name varchar;
  V_emp_name varchar;
  V_emai_id varchar;
  D_doj date;
  I_null_cal integer;
BEGIN

select count(*) into null_cal from emp_gen.employee_data ;
--check if the table is empty 
--if table is empty inserts one row of ceo
if null_cal=0 then
    INSERT INTO emp_gen.employee_data(v_name,D_date_of_joining,V_email) values ('1_RAMA','2001-05-08','rama@email.com');
    p_rows:=p_rows-1;
end if;

--iterate for generating p_rows times the employee data rows
for x in 1..p_rows loop
      --find max serial no of employee id
      select max(I_Emp_id)  into V_max_s from emp_gen.employee_data;
      --New employee id is created in sequence
      INSERT INTO emp_gen.employee_data(I_Emp_id)
                  SELECT * FROM generate_series(V_max_s+1, V_max_s+1);
      --Now again we select the max employee id to know the employee id inserted in previous step
      select max(I_Emp_id)  into I_con_name from emp_gen.employee_data;
      --generates random name string of 5 to 10 chars
      SELECT  array_to_string(ARRAY(SELECT chr((97 + round(random() * 25)) :: integer)
                                    FROM generate_series(5,10)), '') into V_rand_name;
      -- forms the employee name in the format if emp_id_random_string_char
      emp_name:=I_con_name||'_'||V_rand_name;
      --formats the emailid
      emai_id:=V_rand_name||'@email.com';
      --generate random date of joining fom 2000-01-01 to yesterday
      select  NOW() +random() * ( timestamp '2000-01-01' -(current_date - INTERVAL '1 day') )into D_doj ;
      --now update the employee data in the row with doj,name, email_id
      execute 'update  emp_gen.employee_data set v_name=$1,D_date_of_joining=$2,V_email=$3 where I_Emp_id =$4 ' using V_emp_name,D_doj,V_emai_id,I_con_name::integer;
      --raise notice '%',doj;
end loop;

END;
$$ LANGUAGE PLPGSQL;